// example of custom API
import groovy.json.JsonSlurperClassic // thu vien parse json

@NonCPS
def jsonParse(def json) { // ham parse json thanh object
    new groovy.json.JsonSlurperClassic().parseText(json)
}

def repo = "edwardviaene/jenkins-course"

// get toke duoi dang json request den post den url
def token = httpRequest authentication: 'bitbucket-oauth', contentType: 'APPLICATION_FORM', httpMode: 'POST', requestBody: 'grant_type=client_credentials', url: 'https://bitbucket.org/site/oauth2/access_token'
// parse ra lay token
def accessToken = jsonParse(token.content).access_token
// request 2
def pr = httpRequest customHeaders: [[maskValue: true, name: 'Authorization', value: 'Bearer ' + accessToken]], url: "https://api.bitbucket.org/2.0/repositories/${repo}/pullrequests"
// print gia tri
for (p in jsonParse(pr.content).values) { 
    println(p.source.branch.name)
}
